### ISSUE TITLE
Usage for "replacing" cloud code 

### ISSUE THREAD

**Issue by nickoneill** [kylemcc/parse#1]
This is awesome! I've been looking for something like this for a while.

My goal is to write more cloud code related stuff in Go, rather than using the express.js stuff they have built in (which is hard to test). This would be predicated by having a good way to access the current user and perform actions as them.

The current user, in this case, is a user logged in on an iOS device. So my first thought is that I would have to pass session tokens to my server (under ssl, of course) and then use something similar to the "become" method they have for other client libraries. Then I would have access to a user/session that could use the normal create/update/query etc.

Do you think this makes sense for this library?

**Comment by kylemcc** [comment]
Thanks Nick! Glad you might find this useful. This problem has crossed my mind as well. I haven't had a need for this functionality yet, but I will in the future, so I'd be happy to see this included.

If you're interested in submitting a patch, I'd be happy to accept it. It should be a pretty easy addition - take a look at the Login function in [session.go](https://github.com/kylemcc/parse/blob/master/session.go). I was thinking a modified version that uses the /users/me endpoint to verify the token and return a new session.

Otherwise, I may have some time over the weekend to put something together.

**Comment by nickoneill** [comment]
I will check it out! Thanks for the pointer!

**Comment by kylemcc** [comment]
Had some free time, so I decided to knock this out. Usage should look something like:

```go
s, err := parse.Become("sessionToken")
if err != nil {
    log.Printf("error logging in: %v\n", err)
}

user := s.User() // Get the user

// Execute various operations as the user
s.Create(&myType)
u, _ := s.NewUpdate(&myType)
q, _ := s.NewQuery(&myType)
```

Let me know if you have any trouble with this or any other part of the library!
